#!/bin/bash
set -e
export PGPASSWORD=$POSTGRES_PASSWORD;
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER $APP_DB_USER WITH PASSWORD '$APP_DB_PASS';
  CREATE DATABASE $APP_DB_NAME;
  GRANT ALL PRIVILEGES ON DATABASE $APP_DB_NAME TO $APP_DB_USER;
  \connect $APP_DB_NAME $APP_DB_USER
  BEGIN;
    CREATE TABLE IF NOT EXISTS $APP_TABLE_NAME (
	  id_usuario SERIAL PRIMARY KEY,
	  nombre_usuario CHAR(20) NOT NULL,
	  cedula_usuario CHAR(10) NOT NULL,
    teléfono_usuario CHAR(10) NOT NULL,
    mail_usuario CHAR(30) NOT NULL
	);
  COMMIT;
EOSQL